#!/usr/bin/env python

import roslib
roslib.load_manifest('exercise4')
import rospy
import sys

class Speaker:

    def __init__(self):
        rospy.init_node('say', anonymous=True):
        self.speak_sub = rospy.Subscriber("/speech", String, self.speech_callback)
        self.soundhandle = SoundClient()
        rospy.sleep(1)
        self.voice = 'voice_kal_diphone'
        self.volume = 1.0
        self.soundhandle.say("online",self,vouce,self.volume)


    def speech_callback(self, String phrase):
        self.soundhandle.say(phrase,self,vouce,self.volume)

def main(args):

    speaker = Speaker()

    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")


if __name__ == '__main__':
    main(sys.argv)
