#!/usr/bin/env python

import roslib
import rospy
import time

from std_msgs.msg import Int8

if __name__=="__main__":
    rospy.init_node("auto_manipulate")
    pub = rospy.Publisher("set_manipulator_position", Int8)
    for i in range(-1, 5):
        pub.publish(i)
        time.sleep(2)
    pub.publish(0)